require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConversionPopulatorsController do

  # This should return the minimal set of attributes required to create a valid
  # ConversionPopulator. As you add validations to ConversionPopulator, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "date" => "2013-12-01" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConversionPopulatorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all conversion_populators as @conversion_populators" do
      conversion_populator = ConversionPopulator.create! valid_attributes
      get :index, {}, valid_session
      assigns(:conversion_populators).should eq([conversion_populator])
    end
  end

  describe "GET show" do
    it "assigns the requested conversion_populator as @conversion_populator" do
      conversion_populator = ConversionPopulator.create! valid_attributes
      get :show, {:id => conversion_populator.to_param}, valid_session
      assigns(:conversion_populator).should eq(conversion_populator)
    end
  end

  describe "GET new" do
    it "assigns a new conversion_populator as @conversion_populator" do
      get :new, {}, valid_session
      assigns(:conversion_populator).should be_a_new(ConversionPopulator)
    end
  end

  describe "GET edit" do
    it "assigns the requested conversion_populator as @conversion_populator" do
      conversion_populator = ConversionPopulator.create! valid_attributes
      get :edit, {:id => conversion_populator.to_param}, valid_session
      assigns(:conversion_populator).should eq(conversion_populator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ConversionPopulator" do
        expect {
          post :create, {:conversion_populator => valid_attributes}, valid_session
        }.to change(ConversionPopulator, :count).by(1)
      end

      it "assigns a newly created conversion_populator as @conversion_populator" do
        post :create, {:conversion_populator => valid_attributes}, valid_session
        assigns(:conversion_populator).should be_a(ConversionPopulator)
        assigns(:conversion_populator).should be_persisted
      end

      it "redirects to the created conversion_populator" do
        post :create, {:conversion_populator => valid_attributes}, valid_session
        response.should redirect_to(ConversionPopulator.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved conversion_populator as @conversion_populator" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConversionPopulator.any_instance.stub(:save).and_return(false)
        post :create, {:conversion_populator => { "date" => "invalid value" }}, valid_session
        assigns(:conversion_populator).should be_a_new(ConversionPopulator)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConversionPopulator.any_instance.stub(:save).and_return(false)
        post :create, {:conversion_populator => { "date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested conversion_populator" do
        conversion_populator = ConversionPopulator.create! valid_attributes
        # Assuming there are no other conversion_populators in the database, this
        # specifies that the ConversionPopulator created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ConversionPopulator.any_instance.should_receive(:update).with({ "date" => "2013-12-01" })
        put :update, {:id => conversion_populator.to_param, :conversion_populator => { "date" => "2013-12-01" }}, valid_session
      end

      it "assigns the requested conversion_populator as @conversion_populator" do
        conversion_populator = ConversionPopulator.create! valid_attributes
        put :update, {:id => conversion_populator.to_param, :conversion_populator => valid_attributes}, valid_session
        assigns(:conversion_populator).should eq(conversion_populator)
      end

      it "redirects to the conversion_populator" do
        conversion_populator = ConversionPopulator.create! valid_attributes
        put :update, {:id => conversion_populator.to_param, :conversion_populator => valid_attributes}, valid_session
        response.should redirect_to(conversion_populator)
      end
    end

    describe "with invalid params" do
      it "assigns the conversion_populator as @conversion_populator" do
        conversion_populator = ConversionPopulator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConversionPopulator.any_instance.stub(:save).and_return(false)
        put :update, {:id => conversion_populator.to_param, :conversion_populator => { "date" => "invalid value" }}, valid_session
        assigns(:conversion_populator).should eq(conversion_populator)
      end

      it "re-renders the 'edit' template" do
        conversion_populator = ConversionPopulator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConversionPopulator.any_instance.stub(:save).and_return(false)
        put :update, {:id => conversion_populator.to_param, :conversion_populator => { "date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested conversion_populator" do
      conversion_populator = ConversionPopulator.create! valid_attributes
      expect {
        delete :destroy, {:id => conversion_populator.to_param}, valid_session
      }.to change(ConversionPopulator, :count).by(-1)
    end

    it "redirects to the conversion_populators list" do
      conversion_populator = ConversionPopulator.create! valid_attributes
      delete :destroy, {:id => conversion_populator.to_param}, valid_session
      response.should redirect_to(conversion_populators_url)
    end
  end

end
