require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CurrencyConversionsController do

  # This should return the minimal set of attributes required to create a valid
  # CurrencyConversion. As you add validations to CurrencyConversion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "from_code" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CurrencyConversionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all currency_conversions as @currency_conversions" do
      currency_conversion = CurrencyConversion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:currency_conversions).should eq([currency_conversion])
    end
  end

  describe "GET show" do
    it "assigns the requested currency_conversion as @currency_conversion" do
      currency_conversion = CurrencyConversion.create! valid_attributes
      get :show, {:id => currency_conversion.to_param}, valid_session
      assigns(:currency_conversion).should eq(currency_conversion)
    end
  end

  describe "GET new" do
    it "assigns a new currency_conversion as @currency_conversion" do
      get :new, {}, valid_session
      assigns(:currency_conversion).should be_a_new(CurrencyConversion)
    end
  end

  describe "GET edit" do
    it "assigns the requested currency_conversion as @currency_conversion" do
      currency_conversion = CurrencyConversion.create! valid_attributes
      get :edit, {:id => currency_conversion.to_param}, valid_session
      assigns(:currency_conversion).should eq(currency_conversion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CurrencyConversion" do
        expect {
          post :create, {:currency_conversion => valid_attributes}, valid_session
        }.to change(CurrencyConversion, :count).by(1)
      end

      it "assigns a newly created currency_conversion as @currency_conversion" do
        post :create, {:currency_conversion => valid_attributes}, valid_session
        assigns(:currency_conversion).should be_a(CurrencyConversion)
        assigns(:currency_conversion).should be_persisted
      end

      it "redirects to the created currency_conversion" do
        post :create, {:currency_conversion => valid_attributes}, valid_session
        response.should redirect_to(CurrencyConversion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved currency_conversion as @currency_conversion" do
        # Trigger the behavior that occurs when invalid params are submitted
        CurrencyConversion.any_instance.stub(:save).and_return(false)
        post :create, {:currency_conversion => { "from_code" => "invalid value" }}, valid_session
        assigns(:currency_conversion).should be_a_new(CurrencyConversion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CurrencyConversion.any_instance.stub(:save).and_return(false)
        post :create, {:currency_conversion => { "from_code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested currency_conversion" do
        currency_conversion = CurrencyConversion.create! valid_attributes
        # Assuming there are no other currency_conversions in the database, this
        # specifies that the CurrencyConversion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CurrencyConversion.any_instance.should_receive(:update).with({ "from_code" => "" })
        put :update, {:id => currency_conversion.to_param, :currency_conversion => { "from_code" => "" }}, valid_session
      end

      it "assigns the requested currency_conversion as @currency_conversion" do
        currency_conversion = CurrencyConversion.create! valid_attributes
        put :update, {:id => currency_conversion.to_param, :currency_conversion => valid_attributes}, valid_session
        assigns(:currency_conversion).should eq(currency_conversion)
      end

      it "redirects to the currency_conversion" do
        currency_conversion = CurrencyConversion.create! valid_attributes
        put :update, {:id => currency_conversion.to_param, :currency_conversion => valid_attributes}, valid_session
        response.should redirect_to(currency_conversion)
      end
    end

    describe "with invalid params" do
      it "assigns the currency_conversion as @currency_conversion" do
        currency_conversion = CurrencyConversion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CurrencyConversion.any_instance.stub(:save).and_return(false)
        put :update, {:id => currency_conversion.to_param, :currency_conversion => { "from_code" => "invalid value" }}, valid_session
        assigns(:currency_conversion).should eq(currency_conversion)
      end

      it "re-renders the 'edit' template" do
        currency_conversion = CurrencyConversion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CurrencyConversion.any_instance.stub(:save).and_return(false)
        put :update, {:id => currency_conversion.to_param, :currency_conversion => { "from_code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested currency_conversion" do
      currency_conversion = CurrencyConversion.create! valid_attributes
      expect {
        delete :destroy, {:id => currency_conversion.to_param}, valid_session
      }.to change(CurrencyConversion, :count).by(-1)
    end

    it "redirects to the currency_conversions list" do
      currency_conversion = CurrencyConversion.create! valid_attributes
      delete :destroy, {:id => currency_conversion.to_param}, valid_session
      response.should redirect_to(currency_conversions_url)
    end
  end

end
